import Head from "next/head";
import Image from "next/image";
import styles from "../src/styles/Home.module.css";

import Header from "../src/components/header";

export default function Home() {
  return (
    <div /* className={styles.container} */>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <h1>Esto es el contenido</h1>
      </main>
      <footer>
        <h3>Esto es el footer</h3>
      </footer>
    </div>
  );
}
